apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-webapp
  labels:
    app: welcome-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-webapp
  template:
    metadata:
      labels:
        app: welcome-webapp
    spec:
      containers:
        - name: web
          image: welcome-webapp:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ENV_NAME
              value: base
            - name: BG_COLOR
              value: "#334155"
            - name: GREETING
              value: Welcome
            - name: IMAGE_TAG
              value: local
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: welcome-webapp
  labels:
    app: welcome-webapp
spec:
  selector:
    app: welcome-webapp
  ports:
    - name: http
      port: 80
      targetPort: 8080
