apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/name: welcome-webapp
      app.kubernetes.io/part-of: platform-engineering-sandbox
    includeSelectors: false
