apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
        - name: ui
          image: joxit/docker-registry-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          env:
            - name: REGISTRY_TITLE
              value: "OTel Kafka POC Registry"
            - name: REGISTRY_URL
              value: "http://127.0.0.1:30501"
            - name: DELETE_IMAGES
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: registry
spec:
  selector:
    app: registry-ui
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30502
