apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: observability
type: Opaque
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: "thanos"
      endpoint: "minio.observability.svc.cluster.local:9000"
      access_key: "minioadmin"
      secret_key: "minioadmin"
      insecure: true
