apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: otel-kafka-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: producer
          image: 127.0.0.1:30501/otel-kafka-producer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: OTEL_SERVICE_NAME
              value: producer-service
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092
            - name: KAFKA_TOPIC
              value: telemetry-test
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms32m -Xmx128m"
