apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: otel-kafka-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
      annotations:
        instrumentation.opentelemetry.io/inject-python: "otel-kafka-auto"
    spec:
      containers:
        - name: consumer
          image: localhost:5001/otel-kafka-consumer:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092
            - name: KAFKA_TOPIC
              value: telemetry-test
