apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: welcome-webapp-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaganduraisamy/platform-engineering-sandbox.git
    targetRevision: lab/gitops-argocd # TODO: switch to main once merged
    path: 7_kustomize-webapp/kustomize/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: welcome-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
