apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: otel-kafka-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
      annotations:
        instrumentation.opentelemetry.io/inject-java: "otel-kafka-auto"
    spec:
      containers:
        - name: producer
          image: localhost:5001/otel-kafka-producer:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092
            - name: KAFKA_TOPIC
              value: telemetry-test
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms32m -Xmx128m"
